version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: studentmanager
    restart: always   # Riavvia il DB se crasha o se il server riparte
    environment:
      POSTGRES_DB: studentmanager
      POSTGRES_USER: ema
      POSTGRES_PASSWORD: emaema
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data   # Persistenza dati
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
